root = "."
tmp_dir = "tmp"

[build]
cmd = "just backend build"
bin = "./tmp/bin/swoptape"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "frontend", "node_modules", "data"]
exclude_regex = ["_test.go"]
include_ext = ["go", "toml"]
kill_delay = "0s"
send_interrupt = true
stop_on_error = true

[log]
time = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
